//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationClient.HotelServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.hotelserver/", ConfigurationName="HotelServer.HotelServer")]
    public interface HotelServer {
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getServerNameRequest", ReplyAction="http://ws.hotelserver/HotelServer/getServerNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelReservationClient.HotelServer.getServerNameResponse getServerName(HotelReservationClient.HotelServer.getServerNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getServerNameRequest", ReplyAction="http://ws.hotelserver/HotelServer/getServerNameResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getServerNameResponse> getServerNameAsync(HotelReservationClient.HotelServer.getServerNameRequest request);
        
        // CODEGEN: Parametr „roomNumber” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/addRoomRequest", ReplyAction="http://ws.hotelserver/HotelServer/addRoomResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HotelReservationClient.HotelServer.addRoomResponse addRoom(HotelReservationClient.HotelServer.addRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/addRoomRequest", ReplyAction="http://ws.hotelserver/HotelServer/addRoomResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.addRoomResponse> addRoomAsync(HotelReservationClient.HotelServer.addRoomRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/deleteRoomRequest", ReplyAction="http://ws.hotelserver/HotelServer/deleteRoomResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelReservationClient.HotelServer.deleteRoomResponse deleteRoom(HotelReservationClient.HotelServer.deleteRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/deleteRoomRequest", ReplyAction="http://ws.hotelserver/HotelServer/deleteRoomResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.deleteRoomResponse> deleteRoomAsync(HotelReservationClient.HotelServer.deleteRoomRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getReservationsRequest", ReplyAction="http://ws.hotelserver/HotelServer/getReservationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelReservationClient.HotelServer.getReservationsResponse getReservations(HotelReservationClient.HotelServer.getReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getReservationsRequest", ReplyAction="http://ws.hotelserver/HotelServer/getReservationsResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getReservationsResponse> getReservationsAsync(HotelReservationClient.HotelServer.getReservationsRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getRoomsRequest", ReplyAction="http://ws.hotelserver/HotelServer/getRoomsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelReservationClient.HotelServer.getRoomsResponse getRooms(HotelReservationClient.HotelServer.getRoomsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getRoomsRequest", ReplyAction="http://ws.hotelserver/HotelServer/getRoomsResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getRoomsResponse> getRoomsAsync(HotelReservationClient.HotelServer.getRoomsRequest request);
        
        // CODEGEN: Parametr „roomId” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/editRoomRequest", ReplyAction="http://ws.hotelserver/HotelServer/editRoomResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HotelReservationClient.HotelServer.editRoomResponse editRoom(HotelReservationClient.HotelServer.editRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/editRoomRequest", ReplyAction="http://ws.hotelserver/HotelServer/editRoomResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.editRoomResponse> editRoomAsync(HotelReservationClient.HotelServer.editRoomRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getRoomRequest", ReplyAction="http://ws.hotelserver/HotelServer/getRoomResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelReservationClient.HotelServer.getRoomResponse getRoom(HotelReservationClient.HotelServer.getRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getRoomRequest", ReplyAction="http://ws.hotelserver/HotelServer/getRoomResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getRoomResponse> getRoomAsync(HotelReservationClient.HotelServer.getRoomRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/addReservationRequest", ReplyAction="http://ws.hotelserver/HotelServer/addReservationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelReservationClient.HotelServer.addReservationResponse addReservation(HotelReservationClient.HotelServer.addReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/addReservationRequest", ReplyAction="http://ws.hotelserver/HotelServer/addReservationResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.addReservationResponse> addReservationAsync(HotelReservationClient.HotelServer.addReservationRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getReservationRequest", ReplyAction="http://ws.hotelserver/HotelServer/getReservationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelReservationClient.HotelServer.getReservationResponse getReservation(HotelReservationClient.HotelServer.getReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getReservationRequest", ReplyAction="http://ws.hotelserver/HotelServer/getReservationResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getReservationResponse> getReservationAsync(HotelReservationClient.HotelServer.getReservationRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getRoomReservationsRequest", ReplyAction="http://ws.hotelserver/HotelServer/getRoomReservationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelReservationClient.HotelServer.getRoomReservationsResponse getRoomReservations(HotelReservationClient.HotelServer.getRoomReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/getRoomReservationsRequest", ReplyAction="http://ws.hotelserver/HotelServer/getRoomReservationsResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getRoomReservationsResponse> getRoomReservationsAsync(HotelReservationClient.HotelServer.getRoomReservationsRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/deleteReservationRequest", ReplyAction="http://ws.hotelserver/HotelServer/deleteReservationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelReservationClient.HotelServer.deleteReservationResponse deleteReservation(HotelReservationClient.HotelServer.deleteReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.hotelserver/HotelServer/deleteReservationRequest", ReplyAction="http://ws.hotelserver/HotelServer/deleteReservationResponse")]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.deleteReservationResponse> deleteReservationAsync(HotelReservationClient.HotelServer.deleteReservationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServerName", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getServerNameRequest {
        
        public getServerNameRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServerNameResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getServerNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getServerNameResponse() {
        }
        
        public getServerNameResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addRoom", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class addRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int roomNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int bedsAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notes;
        
        public addRoomRequest() {
        }
        
        public addRoomRequest(int roomNumber, int bedsAmount, double price, string notes) {
            this.roomNumber = roomNumber;
            this.bedsAmount = bedsAmount;
            this.price = price;
            this.notes = notes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addRoomResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class addRoomResponse {
        
        public addRoomResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRoom", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class deleteRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int roomId;
        
        public deleteRoomRequest() {
        }
        
        public deleteRoomRequest(int roomId) {
            this.roomId = roomId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRoomResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class deleteRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteRoomResponse() {
        }
        
        public deleteRoomResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.hotelserver/")]
    public partial class reservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateFromField;
        
        private bool dateFromFieldSpecified;
        
        private System.DateTime dateToField;
        
        private bool dateToFieldSpecified;
        
        private int daysAmountField;
        
        private double priceField;
        
        private int reservationIdField;
        
        private int roomIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
                this.RaisePropertyChanged("dateFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateFromSpecified {
            get {
                return this.dateFromFieldSpecified;
            }
            set {
                this.dateFromFieldSpecified = value;
                this.RaisePropertyChanged("dateFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
                this.RaisePropertyChanged("dateTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateToSpecified {
            get {
                return this.dateToFieldSpecified;
            }
            set {
                this.dateToFieldSpecified = value;
                this.RaisePropertyChanged("dateToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int daysAmount {
            get {
                return this.daysAmountField;
            }
            set {
                this.daysAmountField = value;
                this.RaisePropertyChanged("daysAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int reservationId {
            get {
                return this.reservationIdField;
            }
            set {
                this.reservationIdField = value;
                this.RaisePropertyChanged("reservationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int roomId {
            get {
                return this.roomIdField;
            }
            set {
                this.roomIdField = value;
                this.RaisePropertyChanged("roomId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.hotelserver/")]
    public partial class room : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int bedsAmountField;
        
        private string notesField;
        
        private double priceField;
        
        private int roomIdField;
        
        private int roomNumberField;
        
        private reservation[] roomReservationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int bedsAmount {
            get {
                return this.bedsAmountField;
            }
            set {
                this.bedsAmountField = value;
                this.RaisePropertyChanged("bedsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int roomId {
            get {
                return this.roomIdField;
            }
            set {
                this.roomIdField = value;
                this.RaisePropertyChanged("roomId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int roomNumber {
            get {
                return this.roomNumberField;
            }
            set {
                this.roomNumberField = value;
                this.RaisePropertyChanged("roomNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("roomReservations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public reservation[] roomReservations {
            get {
                return this.roomReservationsField;
            }
            set {
                this.roomReservationsField = value;
                this.RaisePropertyChanged("roomReservations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReservations", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getReservationsRequest {
        
        public getReservationsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReservationsResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HotelReservationClient.HotelServer.reservation[] @return;
        
        public getReservationsResponse() {
        }
        
        public getReservationsResponse(HotelReservationClient.HotelServer.reservation[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRooms", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getRoomsRequest {
        
        public getRoomsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoomsResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HotelReservationClient.HotelServer.room[] @return;
        
        public getRoomsResponse() {
        }
        
        public getRoomsResponse(HotelReservationClient.HotelServer.room[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editRoom", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class editRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int roomId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int roomNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int bedsAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notes;
        
        public editRoomRequest() {
        }
        
        public editRoomRequest(int roomId, int roomNumber, int bedsAmount, double price, string notes) {
            this.roomId = roomId;
            this.roomNumber = roomNumber;
            this.bedsAmount = bedsAmount;
            this.price = price;
            this.notes = notes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editRoomResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class editRoomResponse {
        
        public editRoomResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoom", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int roomId;
        
        public getRoomRequest() {
        }
        
        public getRoomRequest(int roomId) {
            this.roomId = roomId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoomResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HotelReservationClient.HotelServer.room @return;
        
        public getRoomResponse() {
        }
        
        public getRoomResponse(HotelReservationClient.HotelServer.room @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addReservation", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class addReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int roomId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateTo;
        
        public addReservationRequest() {
        }
        
        public addReservationRequest(int roomId, System.DateTime dateFrom, System.DateTime dateTo) {
            this.roomId = roomId;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addReservationResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class addReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public addReservationResponse() {
        }
        
        public addReservationResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReservation", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int reservationId;
        
        public getReservationRequest() {
        }
        
        public getReservationRequest(int reservationId) {
            this.reservationId = reservationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReservationResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HotelReservationClient.HotelServer.reservation @return;
        
        public getReservationResponse() {
        }
        
        public getReservationResponse(HotelReservationClient.HotelServer.reservation @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoomReservations", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getRoomReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int roomId;
        
        public getRoomReservationsRequest() {
        }
        
        public getRoomReservationsRequest(int roomId) {
            this.roomId = roomId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoomReservationsResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class getRoomReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HotelReservationClient.HotelServer.reservation[] @return;
        
        public getRoomReservationsResponse() {
        }
        
        public getRoomReservationsResponse(HotelReservationClient.HotelServer.reservation[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteReservation", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class deleteReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int reservationId;
        
        public deleteReservationRequest() {
        }
        
        public deleteReservationRequest(int reservationId) {
            this.reservationId = reservationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteReservationResponse", WrapperNamespace="http://ws.hotelserver/", IsWrapped=true)]
    public partial class deleteReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.hotelserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteReservationResponse() {
        }
        
        public deleteReservationResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelServerChannel : HotelReservationClient.HotelServer.HotelServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelServerClient : System.ServiceModel.ClientBase<HotelReservationClient.HotelServer.HotelServer>, HotelReservationClient.HotelServer.HotelServer {
        
        public HotelServerClient() {
        }
        
        public HotelServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.getServerNameResponse HotelReservationClient.HotelServer.HotelServer.getServerName(HotelReservationClient.HotelServer.getServerNameRequest request) {
            return base.Channel.getServerName(request);
        }
        
        public string getServerName() {
            HotelReservationClient.HotelServer.getServerNameRequest inValue = new HotelReservationClient.HotelServer.getServerNameRequest();
            HotelReservationClient.HotelServer.getServerNameResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).getServerName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getServerNameResponse> HotelReservationClient.HotelServer.HotelServer.getServerNameAsync(HotelReservationClient.HotelServer.getServerNameRequest request) {
            return base.Channel.getServerNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getServerNameResponse> getServerNameAsync() {
            HotelReservationClient.HotelServer.getServerNameRequest inValue = new HotelReservationClient.HotelServer.getServerNameRequest();
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).getServerNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.addRoomResponse HotelReservationClient.HotelServer.HotelServer.addRoom(HotelReservationClient.HotelServer.addRoomRequest request) {
            return base.Channel.addRoom(request);
        }
        
        public void addRoom(int roomNumber, int bedsAmount, double price, string notes) {
            HotelReservationClient.HotelServer.addRoomRequest inValue = new HotelReservationClient.HotelServer.addRoomRequest();
            inValue.roomNumber = roomNumber;
            inValue.bedsAmount = bedsAmount;
            inValue.price = price;
            inValue.notes = notes;
            HotelReservationClient.HotelServer.addRoomResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).addRoom(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.addRoomResponse> HotelReservationClient.HotelServer.HotelServer.addRoomAsync(HotelReservationClient.HotelServer.addRoomRequest request) {
            return base.Channel.addRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.addRoomResponse> addRoomAsync(int roomNumber, int bedsAmount, double price, string notes) {
            HotelReservationClient.HotelServer.addRoomRequest inValue = new HotelReservationClient.HotelServer.addRoomRequest();
            inValue.roomNumber = roomNumber;
            inValue.bedsAmount = bedsAmount;
            inValue.price = price;
            inValue.notes = notes;
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).addRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.deleteRoomResponse HotelReservationClient.HotelServer.HotelServer.deleteRoom(HotelReservationClient.HotelServer.deleteRoomRequest request) {
            return base.Channel.deleteRoom(request);
        }
        
        public bool deleteRoom(int roomId) {
            HotelReservationClient.HotelServer.deleteRoomRequest inValue = new HotelReservationClient.HotelServer.deleteRoomRequest();
            inValue.roomId = roomId;
            HotelReservationClient.HotelServer.deleteRoomResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).deleteRoom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.deleteRoomResponse> HotelReservationClient.HotelServer.HotelServer.deleteRoomAsync(HotelReservationClient.HotelServer.deleteRoomRequest request) {
            return base.Channel.deleteRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.deleteRoomResponse> deleteRoomAsync(int roomId) {
            HotelReservationClient.HotelServer.deleteRoomRequest inValue = new HotelReservationClient.HotelServer.deleteRoomRequest();
            inValue.roomId = roomId;
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).deleteRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.getReservationsResponse HotelReservationClient.HotelServer.HotelServer.getReservations(HotelReservationClient.HotelServer.getReservationsRequest request) {
            return base.Channel.getReservations(request);
        }
        
        public HotelReservationClient.HotelServer.reservation[] getReservations() {
            HotelReservationClient.HotelServer.getReservationsRequest inValue = new HotelReservationClient.HotelServer.getReservationsRequest();
            HotelReservationClient.HotelServer.getReservationsResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).getReservations(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getReservationsResponse> HotelReservationClient.HotelServer.HotelServer.getReservationsAsync(HotelReservationClient.HotelServer.getReservationsRequest request) {
            return base.Channel.getReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getReservationsResponse> getReservationsAsync() {
            HotelReservationClient.HotelServer.getReservationsRequest inValue = new HotelReservationClient.HotelServer.getReservationsRequest();
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).getReservationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.getRoomsResponse HotelReservationClient.HotelServer.HotelServer.getRooms(HotelReservationClient.HotelServer.getRoomsRequest request) {
            return base.Channel.getRooms(request);
        }
        
        public HotelReservationClient.HotelServer.room[] getRooms() {
            HotelReservationClient.HotelServer.getRoomsRequest inValue = new HotelReservationClient.HotelServer.getRoomsRequest();
            HotelReservationClient.HotelServer.getRoomsResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).getRooms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getRoomsResponse> HotelReservationClient.HotelServer.HotelServer.getRoomsAsync(HotelReservationClient.HotelServer.getRoomsRequest request) {
            return base.Channel.getRoomsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getRoomsResponse> getRoomsAsync() {
            HotelReservationClient.HotelServer.getRoomsRequest inValue = new HotelReservationClient.HotelServer.getRoomsRequest();
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).getRoomsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.editRoomResponse HotelReservationClient.HotelServer.HotelServer.editRoom(HotelReservationClient.HotelServer.editRoomRequest request) {
            return base.Channel.editRoom(request);
        }
        
        public void editRoom(int roomId, int roomNumber, int bedsAmount, double price, string notes) {
            HotelReservationClient.HotelServer.editRoomRequest inValue = new HotelReservationClient.HotelServer.editRoomRequest();
            inValue.roomId = roomId;
            inValue.roomNumber = roomNumber;
            inValue.bedsAmount = bedsAmount;
            inValue.price = price;
            inValue.notes = notes;
            HotelReservationClient.HotelServer.editRoomResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).editRoom(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.editRoomResponse> HotelReservationClient.HotelServer.HotelServer.editRoomAsync(HotelReservationClient.HotelServer.editRoomRequest request) {
            return base.Channel.editRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.editRoomResponse> editRoomAsync(int roomId, int roomNumber, int bedsAmount, double price, string notes) {
            HotelReservationClient.HotelServer.editRoomRequest inValue = new HotelReservationClient.HotelServer.editRoomRequest();
            inValue.roomId = roomId;
            inValue.roomNumber = roomNumber;
            inValue.bedsAmount = bedsAmount;
            inValue.price = price;
            inValue.notes = notes;
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).editRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.getRoomResponse HotelReservationClient.HotelServer.HotelServer.getRoom(HotelReservationClient.HotelServer.getRoomRequest request) {
            return base.Channel.getRoom(request);
        }
        
        public HotelReservationClient.HotelServer.room getRoom(int roomId) {
            HotelReservationClient.HotelServer.getRoomRequest inValue = new HotelReservationClient.HotelServer.getRoomRequest();
            inValue.roomId = roomId;
            HotelReservationClient.HotelServer.getRoomResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).getRoom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getRoomResponse> HotelReservationClient.HotelServer.HotelServer.getRoomAsync(HotelReservationClient.HotelServer.getRoomRequest request) {
            return base.Channel.getRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getRoomResponse> getRoomAsync(int roomId) {
            HotelReservationClient.HotelServer.getRoomRequest inValue = new HotelReservationClient.HotelServer.getRoomRequest();
            inValue.roomId = roomId;
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).getRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.addReservationResponse HotelReservationClient.HotelServer.HotelServer.addReservation(HotelReservationClient.HotelServer.addReservationRequest request) {
            return base.Channel.addReservation(request);
        }
        
        public bool addReservation(int roomId, System.DateTime dateFrom, System.DateTime dateTo) {
            HotelReservationClient.HotelServer.addReservationRequest inValue = new HotelReservationClient.HotelServer.addReservationRequest();
            inValue.roomId = roomId;
            inValue.dateFrom = dateFrom;
            inValue.dateTo = dateTo;
            HotelReservationClient.HotelServer.addReservationResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).addReservation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.addReservationResponse> HotelReservationClient.HotelServer.HotelServer.addReservationAsync(HotelReservationClient.HotelServer.addReservationRequest request) {
            return base.Channel.addReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.addReservationResponse> addReservationAsync(int roomId, System.DateTime dateFrom, System.DateTime dateTo) {
            HotelReservationClient.HotelServer.addReservationRequest inValue = new HotelReservationClient.HotelServer.addReservationRequest();
            inValue.roomId = roomId;
            inValue.dateFrom = dateFrom;
            inValue.dateTo = dateTo;
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).addReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.getReservationResponse HotelReservationClient.HotelServer.HotelServer.getReservation(HotelReservationClient.HotelServer.getReservationRequest request) {
            return base.Channel.getReservation(request);
        }
        
        public HotelReservationClient.HotelServer.reservation getReservation(int reservationId) {
            HotelReservationClient.HotelServer.getReservationRequest inValue = new HotelReservationClient.HotelServer.getReservationRequest();
            inValue.reservationId = reservationId;
            HotelReservationClient.HotelServer.getReservationResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).getReservation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getReservationResponse> HotelReservationClient.HotelServer.HotelServer.getReservationAsync(HotelReservationClient.HotelServer.getReservationRequest request) {
            return base.Channel.getReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getReservationResponse> getReservationAsync(int reservationId) {
            HotelReservationClient.HotelServer.getReservationRequest inValue = new HotelReservationClient.HotelServer.getReservationRequest();
            inValue.reservationId = reservationId;
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).getReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.getRoomReservationsResponse HotelReservationClient.HotelServer.HotelServer.getRoomReservations(HotelReservationClient.HotelServer.getRoomReservationsRequest request) {
            return base.Channel.getRoomReservations(request);
        }
        
        public HotelReservationClient.HotelServer.reservation[] getRoomReservations(int roomId) {
            HotelReservationClient.HotelServer.getRoomReservationsRequest inValue = new HotelReservationClient.HotelServer.getRoomReservationsRequest();
            inValue.roomId = roomId;
            HotelReservationClient.HotelServer.getRoomReservationsResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).getRoomReservations(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getRoomReservationsResponse> HotelReservationClient.HotelServer.HotelServer.getRoomReservationsAsync(HotelReservationClient.HotelServer.getRoomReservationsRequest request) {
            return base.Channel.getRoomReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.getRoomReservationsResponse> getRoomReservationsAsync(int roomId) {
            HotelReservationClient.HotelServer.getRoomReservationsRequest inValue = new HotelReservationClient.HotelServer.getRoomReservationsRequest();
            inValue.roomId = roomId;
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).getRoomReservationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelReservationClient.HotelServer.deleteReservationResponse HotelReservationClient.HotelServer.HotelServer.deleteReservation(HotelReservationClient.HotelServer.deleteReservationRequest request) {
            return base.Channel.deleteReservation(request);
        }
        
        public bool deleteReservation(int reservationId) {
            HotelReservationClient.HotelServer.deleteReservationRequest inValue = new HotelReservationClient.HotelServer.deleteReservationRequest();
            inValue.reservationId = reservationId;
            HotelReservationClient.HotelServer.deleteReservationResponse retVal = ((HotelReservationClient.HotelServer.HotelServer)(this)).deleteReservation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelReservationClient.HotelServer.deleteReservationResponse> HotelReservationClient.HotelServer.HotelServer.deleteReservationAsync(HotelReservationClient.HotelServer.deleteReservationRequest request) {
            return base.Channel.deleteReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelReservationClient.HotelServer.deleteReservationResponse> deleteReservationAsync(int reservationId) {
            HotelReservationClient.HotelServer.deleteReservationRequest inValue = new HotelReservationClient.HotelServer.deleteReservationRequest();
            inValue.reservationId = reservationId;
            return ((HotelReservationClient.HotelServer.HotelServer)(this)).deleteReservationAsync(inValue);
        }
    }
}
